compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: "InternVLA/config/deepseeds/ds_config.yaml"
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
# main_process_port: 12345
num_machines: 1
num_processes: 8